####################################################################################################################
# Configuration file for translations and locales                                                                  #
####################################################################################################################

parameters:

    # array of available interface translations
    interface_translation_locales:
        #italiano
        es:
            code: es
            label: español

    # array of available interfaces translations (simple array format)
    interface_translation_locales_simple_array: [it, en, es]

    # parameter to be used in routes.yml
    # add |[locale] if a new interface locale is available
    route_locale_requirements: '^it|en|es$'